
import './globals.css'
import { Inter } from 'next/font/google';
import { NavBar } from '@/components/NavBar';

import Theme from './Theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <NavBar />
          {children}
        </Theme>
      </body>
    </html>
  )
}
